#!/usr/bin/env bash
# Generates policy-bearing git hook snippets from canonical patterns.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
HOOK_DIR="${SCRIPT_DIR}/../skills/project-setup/assets/hooks"

CHECK=false
TEMP_DIR=""

# Adjacent quotes keep the generated guard from matching its own pattern.
PLANNED_WORK_PATTERN="(will[[:space:]_-]+be[[:space:]_-]+added|will[[:space:]_-]+land|will[[:space:]_-]+follow|coming[[:space:]_-]+soon|next[[:space:]_-]+session|future[[:space:]_-]+work|we[[:space:]_-]+(plan|intend)[[:space:]_-]+to|planned[[:space:]_-]+for|(^|[^[:alnum:]_])(TO''DO|FIX''ME)([^[:alnum:]_]|$))"
BRANCH_PREFIX_GLOB='feat/*|fix/*|refactor/*|perf/*|docs/*|style/*|test/*|build/*|ci/*|chore/*|revert/*'
CONTRIBUTION_VERBS='(generated|written|reviewed|planned|implemented|authored|co-authored|developed|coded)'
DEVELOPMENT_TOOL_SUBJECTS='(ai|llm|assistant|agent|bot|automation|code[[:space:]]+assistant|coding[[:space:]]+(agent|tool))'
PROJECT_ARTIFACTS='(project|code|changes?|commit|implementation|documentation|docs|feature|fix)'
ATTRIBUTION_PATTERN="((co-)?authored''-by:|generated''-by:|written''-by:|reviewed''-by:|planned''-by:|developed''-by:|^[[:space:]>*-]*${CONTRIBUTION_VERBS}[[:space:]]+(by|with|using)[[:space:]]+(an?[[:space:]]+)?${DEVELOPMENT_TOOL_SUBJECTS}([^[:alnum:]_]|$)|(^|[^[:alnum:]_])${PROJECT_ARTIFACTS}[[:space:]]+(was[[:space:]]+)?${CONTRIBUTION_VERBS}[[:space:]]+(by|with|using)[[:space:]]+(an?[[:space:]]+)?${DEVELOPMENT_TOOL_SUBJECTS}([^[:alnum:]_]|$)|(^|[^[:alnum:]_])${DEVELOPMENT_TOOL_SUBJECTS}[[:space:]-]+${CONTRIBUTION_VERBS}[[:space:]]+${PROJECT_ARTIFACTS}([^[:alnum:]_]|$))"

# Prints command usage.
usage() {
  cat <<'EOF'
Usage: scripts/generate-hook-policy.sh [--check]

Options:
  --check     Compare generated hook snippets with their tracked assets.
  -h, --help  Show this help.

Without options, rewrites the policy-bearing hook assets.
EOF
}

# Prints an error and exits unsuccessfully.
die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

# Removes the private generation directory.
cleanup() {
  if [ -n "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
  fi
}

# Emits the staged-content planned-work guard.
emit_pre_commit_banned_phrases() {
  cat <<EOF
# BEGIN agent-guidelines staged banned-phrase guard
# Rejects high-confidence promises and unfinished-work markers from
# added staged lines. The canonical pattern is generated by
# scripts/generate-hook-policy.sh. Plain POSIX sh.
planned_work_pattern='${PLANNED_WORK_PATTERN}'

planned_work_hits="\$(git diff --cached --name-only --diff-filter=ACMR | while IFS= read -r staged_file; do
  case "\$staged_file" in
    rules/no-plans-on-main.md|.agent-guidelines/rules/no-plans-on-main.md)
      continue
      ;;
  esac
  if git diff --cached --unified=0 -- "\$staged_file" |
    sed -n '/^+++ /d; s/^+//p' |
    grep -Ei "\$planned_work_pattern" >/dev/null; then
    printf '  %s\\n' "\$staged_file"
  fi
done)"

if [ -n "\$planned_work_hits" ]; then
  echo "Planned-work promises or unfinished-work markers found in staged content:" >&2
  printf '%s\\n' "\$planned_work_hits" >&2
  echo "Describe current behavior; keep implementation plans outside permanent history." >&2
  exit 1
fi
# END agent-guidelines staged banned-phrase guard
EOF
}

# Emits the commit-message planned-work guard.
emit_commit_msg_banned_phrases() {
  cat <<EOF
# BEGIN agent-guidelines message banned-phrase guard
# Rejects high-confidence promises and unfinished-work markers in
# commit and merge messages. The canonical pattern is generated by
# scripts/generate-hook-policy.sh. Plain POSIX sh.
msg_file="\$1"
planned_work_pattern='${PLANNED_WORK_PATTERN}'

if grep -v '^#' "\$msg_file" | grep -Ei "\$planned_work_pattern" >/dev/null; then
  echo "Planned-work promises or unfinished-work markers found in the commit message:" >&2
  grep -v '^#' "\$msg_file" | grep -Ei "\$planned_work_pattern" | sed 's/^/  /' >&2
  echo "Describe current behavior; keep implementation plans outside permanent history." >&2
  exit 1
fi
# END agent-guidelines message banned-phrase guard
EOF
}

# Emits the staged-content development-attribution guard.
emit_pre_commit_attribution() {
  cat <<EOF
# BEGIN agent-guidelines staged attribution guard
# Rejects high-confidence development authorship from added staged
# lines while allowing functional integration language. The canonical
# Pattern source: scripts/generate-hook-policy.sh. POSIX sh.
attribution_pattern='${ATTRIBUTION_PATTERN}'

attribution_hits="\$(git diff --cached --name-only --diff-filter=ACMR | while IFS= read -r staged_file; do
  if git diff --cached --unified=0 -- "\$staged_file" |
    sed -n '/^+++ /d; s/^+//p' |
    grep -Ei "\$attribution_pattern" >/dev/null; then
    printf '  %s\\n' "\$staged_file"
  fi
done)"

if [ -n "\$attribution_hits" ]; then
  echo "Development-tool authorship found in staged content:" >&2
  printf '%s\\n' "\$attribution_hits" >&2
  echo "Describe functional integrations without crediting development work to a tool." >&2
  exit 1
fi
# END agent-guidelines staged attribution guard
EOF
}

# Emits the commit-message development-attribution guard.
emit_commit_msg_attribution() {
  cat <<EOF
# BEGIN agent-guidelines commit attribution guard
# Rejects the same high-confidence development authorship forms used
# for staged content. Pattern source: scripts/generate-hook-policy.sh.
commit_msg_file="\$1"
attribution_pattern='${ATTRIBUTION_PATTERN}'

if grep -v '^#' "\$commit_msg_file" |
  grep -Ei "\$attribution_pattern" >/dev/null; then
  echo "Development-tool authorship is not allowed in commit messages." >&2
  exit 1
fi
# END agent-guidelines commit attribution guard
EOF
}

# Emits the branch-name and default-branch push guard.
emit_pre_push_branch_name() {
  cat <<EOF
# BEGIN agent-guidelines branch-name guard
# Validates pushed branch refs against the configured default branch,
# canonical work-branch prefixes, and the shared planned-work pattern.
# Deletions, tags, and other non-branch refs remain valid. Generated by
# scripts/generate-hook-policy.sh. Plain POSIX sh.
planned_work_pattern='${PLANNED_WORK_PATTERN}'
worktree_root="\$(git rev-parse --show-toplevel 2>/dev/null || true)"
state_file="\${worktree_root}/.agent-guidelines/config"

if [ -z "\$worktree_root" ] || [ ! -f "\$state_file" ] || [ -L "\$state_file" ]; then
  echo "Cannot resolve the managed default branch from \$state_file." >&2
  echo "Run project setup again with --default-branch when detection is ambiguous." >&2
  exit 1
fi

default_branch_count="\$(grep -c '^default_branch=' "\$state_file" || true)"
if [ "\$default_branch_count" -ne 1 ]; then
  echo "Managed setup state must contain exactly one default_branch value: \$state_file" >&2
  exit 1
fi
default_branch="\$(sed -n 's/^default_branch=//p' "\$state_file")"
if ! git check-ref-format --branch "\$default_branch" >/dev/null 2>&1; then
  echo "Managed setup state contains an invalid default branch: \$state_file" >&2
  exit 1
fi

while read -r local_ref local_sha remote_ref remote_sha; do
  case "\$local_sha" in
    *[!0]*) ;;
    *) continue ;;
  esac

  case "\$remote_ref" in
    refs/heads/*) pushed_branch="\${remote_ref#refs/heads/}" ;;
    *) continue ;;
  esac

  if [ "\$pushed_branch" != "\$default_branch" ]; then
    case "\$pushed_branch" in
      ${BRANCH_PREFIX_GLOB}) ;;
      *)
        echo "Refusing to push '\$pushed_branch': branch names must use \$default_branch or a Conventional Commit type prefix." >&2
        echo "Examples: feat/setup-skill, fix/hook-install" >&2
        exit 1
        ;;
    esac
  fi

  if printf '%s\\n' "\$pushed_branch" |
    grep -Ei "\$planned_work_pattern" >/dev/null; then
    echo "Refusing to push '\$pushed_branch': the name contains a planned-work promise or unfinished-work marker." >&2
    echo "Rename the branch to describe current work." >&2
    exit 1
  fi
done
# END agent-guidelines branch-name guard
EOF
}

# Emits one generated hook asset selected by basename.
render_hook() {
  local hook_name="$1"

  case "$hook_name" in
    pre-commit-attribution) emit_pre_commit_attribution ;;
    pre-commit-banned-phrases) emit_pre_commit_banned_phrases ;;
    commit-msg-attribution) emit_commit_msg_attribution ;;
    commit-msg-banned-phrases) emit_commit_msg_banned_phrases ;;
    pre-push-branch-name) emit_pre_push_branch_name ;;
    *) die "unknown generated hook asset: $hook_name" ;;
  esac
}

# Generates or checks every policy-bearing hook asset.
main() {
  local hook_name generated target
  local stale=false
  local hook_names=(
    pre-commit-attribution
    pre-commit-banned-phrases
    commit-msg-attribution
    commit-msg-banned-phrases
    pre-push-branch-name
  )

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --check) CHECK=true; shift ;;
      -h|--help) usage; return 0 ;;
      *) die "unknown option: $1" ;;
    esac
  done

  [ -d "$HOOK_DIR" ] || die "hook asset directory not found: $HOOK_DIR"
  TEMP_DIR="$(mktemp -d)"
  trap cleanup EXIT

  for hook_name in "${hook_names[@]}"; do
    generated="$TEMP_DIR/$hook_name"
    target="$HOOK_DIR/$hook_name"
    render_hook "$hook_name" > "$generated"

    if [ "$CHECK" = true ]; then
      if ! cmp -s "$target" "$generated"; then
        printf 'stale generated hook asset: %s\n' "$target" >&2
        diff -u "$target" "$generated" >&2 || true
        stale=true
      fi
    elif cmp -s "$target" "$generated"; then
      printf 'unchanged %s\n' "$target"
    else
      chmod 0644 "$generated"
      mv "$generated" "$target"
      printf 'wrote %s\n' "$target"
    fi
  done

  [ "$stale" = false ] || exit 1
  if [ "$CHECK" = true ]; then
    printf 'generated hook policy assets are current\n'
  fi
}

main "$@"
