#!/usr/bin/env bash
# Generates rules/README.md from each rule file's frontmatter.
#
# Every rule under rules/ declares `when:`, `load:`, and `summary:`
# fields. This script assembles the rule catalog from those fields so
# the catalog cannot drift from the rule files themselves. Run it
# after adding, removing, retiering, or resummarizing a rule.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
RULES_DIR="${SCRIPT_DIR}/../rules"
README_PATH="${RULES_DIR}/README.md"

CHECK=false

usage() {
  cat <<'EOF'
Usage: scripts/generate-rules-readme.sh [--check]

Options:
  --check     Compare the generated catalog against rules/README.md and
              exit nonzero if they differ, without writing anything.
  -h, --help  Show this help.

Without options, writes the generated catalog to rules/README.md.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check) CHECK=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

[ -d "$RULES_DIR" ] || die "rules directory not found: $RULES_DIR"

# Prints the single-line value of a frontmatter field, or nothing.
read_field() {
  local file="$1"
  local field="$2"

  awk -v field="$field" '
    NR == 1 && /^---[[:space:]]*$/ { in_fm = 1; next }
    in_fm && /^---[[:space:]]*$/ { exit }
    in_fm && index($0, field ":") == 1 {
      value = $0
      sub(/^[^:]*:[[:space:]]*/, "", value)
      gsub(/[[:space:]]+$/, "", value)
      print value
      exit
    }
  ' "$file"
}

# Prints the indented block lines of a folded `summary: >-` frontmatter
# field with the leading indent stripped, preserving the line wrapping
# used in the rule file.
read_summary() {
  local file="$1"

  awk '
    NR == 1 && /^---[[:space:]]*$/ { in_fm = 1; next }
    in_fm && /^---[[:space:]]*$/ { exit }
    in_fm && /^summary:[[:space:]]*>-?[[:space:]]*$/ { in_sum = 1; next }
    in_fm && in_sum && /^[[:space:]]+[^[:space:]]/ {
      sub(/^[[:space:]]+/, "")
      print
      next
    }
    in_fm && in_sum { exit }
  ' "$file"
}

# Lists rule ids (file basenames without .md) for one load tier, in
# the sorted order the shell glob provides.
rules_in_tier() {
  local tier="$1"
  local file rule

  for file in "$RULES_DIR"/*.md; do
    rule="$(basename "$file" .md)"
    if [ "$rule" = "README" ]; then
      continue
    fi
    if [ "$(read_field "$file" load)" = "$tier" ]; then
      printf '%s\n' "$rule"
    fi
  done
}

# Emits one `### rule` catalog section from the rule's summary field.
emit_rule_section() {
  local rule="$1"
  local file="$RULES_DIR/$rule.md"
  local summary

  summary="$(read_summary "$file")"
  [ -n "$summary" ] || die "missing summary frontmatter field: rules/$rule.md"

  printf '### `%s`\n\n' "$rule"
  printf '%s\n\n' "$summary"
}

generate() {
  local always_rules recall_rules always_count recall_count rule

  always_rules="$(rules_in_tier always)"
  recall_rules="$(rules_in_tier recall)"
  always_count="$(printf '%s\n' "$always_rules" | grep -c .)"
  recall_count="$(printf '%s\n' "$recall_rules" | grep -c .)"

  cat <<EOF
# Rules

> **Generated file.** This catalog is assembled from each rule's
> frontmatter by \`scripts/generate-rules-readme.sh\`. Edit the rule
> files, then regenerate; do not edit this file directly.

Rules live in \`rules/\` as portable, reusable expectations for agents
working in a project. Each rule covers one area of discipline — git
hygiene, attribution, testing, docs, scripts — at a level of generality
that holds across languages and project shapes. A project picks up the
rules it wants through \`project-setup.sh\`, and the four supported
harnesses (Claude Code, OpenCode, Pi, Codex) read them from one
assembled global context file each.

## Frontmatter and Tiering

Every rule file declares YAML frontmatter with three fields:

- **\`when:\`** — a short phrase that completes "Read when X".
  \`setup.sh\` uses it to build the rule router table in the global
  context file, and \`project-setup.sh\` uses it for per-project
  selection.
- **\`load:\`** — either \`always\` (the rule is inlined verbatim into
  every conversation's global context) or \`recall\` (the rule appears
  in the router table only; the model reads its body on demand when
  the trigger matches the current task).
- **\`summary:\`** — a folded block describing the rule for this
  catalog, which \`scripts/generate-rules-readme.sh\` assembles into
  the sections below.

${always_count} rules are tiered \`always\`. They form the baseline a
model follows on every conversation. The remaining ${recall_count} are
tiered \`recall\` and cover situational expectations the model reads
only when needed.

## Always-Loaded Rules

These rules are inlined into the assembled global context file
(\`~/.claude/CLAUDE.md\` and equivalents). The model reads them on
every conversation. Each opens with a Hard Constraints block — the
binding imperatives stated tersely up front — followed by the
rationale and detail sections, so models that weight early tokens
heavily still see every requirement.

EOF

  while IFS= read -r rule; do
    if [ -n "$rule" ]; then
      emit_rule_section "$rule"
    fi
  done <<< "$always_rules"

  cat <<'EOF'
## On-Demand Rules

These rules are listed in the global context router table by their
`when:` trigger and a stable reference path. The model reads them
when a task matches the trigger.

EOF

  while IFS= read -r rule; do
    if [ -n "$rule" ]; then
      emit_rule_section "$rule"
    fi
  done <<< "$recall_rules"
}

TEMP_FILE=""

cleanup() {
  if [ -n "$TEMP_FILE" ]; then
    rm -f "$TEMP_FILE" "${TEMP_FILE}.trimmed"
  fi
}

main() {
  TEMP_FILE="$(mktemp)"
  trap cleanup EXIT

  generate > "$TEMP_FILE"

  # Drop the trailing blank line the last section emits.
  printf '%s\n' "$(cat "$TEMP_FILE")" > "${TEMP_FILE}.trimmed" &&
    mv "${TEMP_FILE}.trimmed" "$TEMP_FILE"

  if [ "$CHECK" = true ]; then
    if cmp -s "$README_PATH" "$TEMP_FILE"; then
      printf 'rules/README.md matches the rule frontmatter\n'
    else
      printf 'rules/README.md is stale; regenerate it with %s\n' \
        'scripts/generate-rules-readme.sh' >&2
      diff -u "$README_PATH" "$TEMP_FILE" >&2 || true
      exit 1
    fi
  else
    mv "$TEMP_FILE" "$README_PATH"
    trap - EXIT
    printf 'wrote %s\n' "$README_PATH"
  fi
}

main "$@"
