#!/usr/bin/env bash
# Generates policy-bearing git hook snippets from canonical patterns.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
HOOK_DIR="${SCRIPT_DIR}/../skills/project-setup/assets/hooks"

CHECK=false
TEMP_DIR=""

# Adjacent quotes keep the generated guard from matching its own pattern.
PLANNED_WORK_PATTERN="(will[[:space:]_-]+be[[:space:]_-]+added|will[[:space:]_-]+land|will[[:space:]_-]+follow|coming[[:space:]_-]+soon|next[[:space:]_-]+session|future[[:space:]_-]+work|we[[:space:]_-]+(plan|intend)[[:space:]_-]+to|planned[[:space:]_-]+for|(^|[^[:alnum:]_])(TO''DO|FIX''ME)([^[:alnum:]_]|$))"

# Prints command usage.
usage() {
  cat <<'EOF'
Usage: scripts/generate-hook-policy.sh [--check]

Options:
  --check     Compare generated hook snippets with their tracked assets.
  -h, --help  Show this help.

Without options, rewrites the policy-bearing hook assets.
EOF
}

# Prints an error and exits unsuccessfully.
die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

# Removes the private generation directory.
cleanup() {
  if [ -n "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
  fi
}

# Emits the staged-content planned-work guard.
emit_pre_commit_banned_phrases() {
  cat <<EOF
# BEGIN agent-guidelines staged banned-phrase guard
# Rejects high-confidence promises and unfinished-work markers from
# added staged lines. The canonical pattern is generated by
# scripts/generate-hook-policy.sh. Plain POSIX sh.
planned_work_pattern='${PLANNED_WORK_PATTERN}'

planned_work_hits="\$(git diff --cached --name-only --diff-filter=ACMR | while IFS= read -r staged_file; do
  case "\$staged_file" in
    rules/no-plans-on-main.md|.agent-guidelines/rules/no-plans-on-main.md)
      continue
      ;;
  esac
  if git diff --cached --unified=0 -- "\$staged_file" |
    sed -n '/^+++ /d; s/^+//p' |
    grep -Ei "\$planned_work_pattern" >/dev/null; then
    printf '  %s\\n' "\$staged_file"
  fi
done)"

if [ -n "\$planned_work_hits" ]; then
  echo "Planned-work promises or unfinished-work markers found in staged content:" >&2
  printf '%s\\n' "\$planned_work_hits" >&2
  echo "Describe current behavior; keep implementation plans outside permanent history." >&2
  exit 1
fi
# END agent-guidelines staged banned-phrase guard
EOF
}

# Emits the commit-message planned-work guard.
emit_commit_msg_banned_phrases() {
  cat <<EOF
# BEGIN agent-guidelines message banned-phrase guard
# Rejects high-confidence promises and unfinished-work markers in
# commit and merge messages. The canonical pattern is generated by
# scripts/generate-hook-policy.sh. Plain POSIX sh.
msg_file="\$1"
planned_work_pattern='${PLANNED_WORK_PATTERN}'

if grep -v '^#' "\$msg_file" | grep -Ei "\$planned_work_pattern" >/dev/null; then
  echo "Planned-work promises or unfinished-work markers found in the commit message:" >&2
  grep -v '^#' "\$msg_file" | grep -Ei "\$planned_work_pattern" | sed 's/^/  /' >&2
  echo "Describe current behavior; keep implementation plans outside permanent history." >&2
  exit 1
fi
# END agent-guidelines message banned-phrase guard
EOF
}

# Emits one generated hook asset selected by basename.
render_hook() {
  local hook_name="$1"

  case "$hook_name" in
    pre-commit-banned-phrases) emit_pre_commit_banned_phrases ;;
    commit-msg-banned-phrases) emit_commit_msg_banned_phrases ;;
    *) die "unknown generated hook asset: $hook_name" ;;
  esac
}

# Generates or checks every policy-bearing hook asset.
main() {
  local hook_name generated target
  local stale=false
  local hook_names=(
    pre-commit-banned-phrases
    commit-msg-banned-phrases
  )

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --check) CHECK=true; shift ;;
      -h|--help) usage; return 0 ;;
      *) die "unknown option: $1" ;;
    esac
  done

  [ -d "$HOOK_DIR" ] || die "hook asset directory not found: $HOOK_DIR"
  TEMP_DIR="$(mktemp -d)"
  trap cleanup EXIT

  for hook_name in "${hook_names[@]}"; do
    generated="$TEMP_DIR/$hook_name"
    target="$HOOK_DIR/$hook_name"
    render_hook "$hook_name" > "$generated"

    if [ "$CHECK" = true ]; then
      if ! cmp -s "$target" "$generated"; then
        printf 'stale generated hook asset: %s\n' "$target" >&2
        diff -u "$target" "$generated" >&2 || true
        stale=true
      fi
    elif cmp -s "$target" "$generated"; then
      printf 'unchanged %s\n' "$target"
    else
      chmod 0644 "$generated"
      mv "$generated" "$target"
      printf 'wrote %s\n' "$target"
    fi
  done

  [ "$stale" = false ] || exit 1
  if [ "$CHECK" = true ]; then
    printf 'generated hook policy assets are current\n'
  fi
}

main "$@"
